---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    If Connie Xian doesn't earn an A, then nobody should, because she had multiple exemplary work that shows her consistently going above and beyond, and asks questions in class that shows her thinking outside of the box.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    The most difficult part of the class was creating functions because it was difficult to ensure it applies to specific inputs, especially for graphs.

3.  What was the easiest part of the class for you? Explain why.

    The easiest part of the class was working on the in class practice activities because I tend to understand the content better when I have the opportunity to talk through problems with peers and get their perspective on how they would solve the problem.

4.  What part of the class surprised or interested you the most? Explain why.

    The most interesting part of the class was learning how to customize graphs and tables because I liked how there were many ways to make analyzing data more intuitive and user friendly through different R packages.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    One piece of advice to a student beginning a quarter of STAT 331 is to constantly revise your thinking because all of the content in the class builds upon each other, and it becomes easier to complete problems if you understand your previous mistakes.
